BaseURL = "http://www.gordonburgett.net"
languageCode = "en-us"
title = "first things first"
author = "Gordon Burgett"
theme="hugo-uno"
copyright = "All content © Gordon Burgett, 2014-2015"

[indexes]
	category = "categories"
	tag = "tags"
[Params]
	AuthorName = "Gordon"
	github = "gburgett"
	email = "gordon@gordonburgett.net"
	description = "A blog about whatever crosses my mind, ordered by importance."

[Languages]
[Languages.en]
	languageName = "English"
	weight = 1

[Languages.sq]
	languageName = "Shqip"
	weight = 2
	description = "Një blog për çfarëdo shkon ndër mend."

[markup.goldmark.renderer]
	unsafe= true